language: objective-c

branches:
 only:
 - master

xcode_project: Swifternalization.xcodeproj
xcode_scheme: SwifternalizationTests
xcode_sdk: iphonesimulator8.3 

script:
- xcodebuild clean build test -project Swifternalization.xcodeproj -scheme SwifternalizationTests

